spring:
  application:
    name: ms-chat
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.23.129:3306/im_chat?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  oss:
    accessKey: 9Rj9lMl9x3hUtjlviQVHGczQ8gDOaCanUqraLzFp
    secretKey: ruOB8qtj-E4OAniq6QSNQfxrScnLF2jPDDPG9aQl
    bucket: milsun
    domainname: https://cloud.gzmilsun.com/
  rabbitmq:
    host: 192.168.23.129
    port: 5673
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated # 开启发送端确认
    publisher-returns: true  # 开启发送消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，以异步发送有限回调returnConfigm
    listener:
      simple:
        acknowledge-mode: manual # 手动ack消息

